version: '2'

services:
  laf:
    build:
      context: .
      dockerfile: ./apps/laf/Dockerfile
      target: development
    command: npm run start:dev laf
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - auth
      - post
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      laf-network:
        aliases:
          - laf

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      laf-network:
        aliases:
          - auth

  post:
    build:
      context: .
      dockerfile: ./apps/post/Dockerfile
      target: development
    command: npm run start:dev post
    env_file:
      - ./.env
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      laf-network:
        aliases:
          - post

  mongodb-primary:
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'
    networks:
      laf-network:
        aliases:
          - mongodb-primary

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      laf-network:
        aliases:
          - mongodb-secondary

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      laf-network:
        aliases:
          - mongodb-arbiter

volumes:
  mongodb_master_data:
    driver: local

networks:
  laf-network:
    driver: bridge